version: '3'

networks:
    laranet:
        external: true
        name: laranet

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  
            - .:/var/www/html 
        ports:
            - "8001:80"
        depends_on:
            - app
        networks:
            - laranet

    mysql:
        image: 'mysql:8'
        container_name: mysql
        ports:
            - "33061:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_DATABASE: 'data_base_name'
            MYSQL_USER: 'homestead'
            MYSQL_PASSWORD: 'secret'
        volumes:
            - 'mydb:/var/lib/mysql'
        networks:
            - laranet
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-psecret" ]
            retries: 3
            timeout: 5s

    redis:
        image: "redis:alpine"
        container_name: redis
        ports:
            - "63791:6379"
        networks:
            - laranet

    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - .:/var/www/html:rw
        working_dir: /var/www/html
        command: ['composer', 'install', '--ignore-platform-reqs', '--no-scripts']

    npm:
        image: node:latest
        container_name: npm
        volumes:
            - ./:/var/www/html:rw
        working_dir: /var/www/html
        entrypoint: ['npm']

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-docker
        volumes:
            - ./:/var/www/html:rw
        depends_on:
            - mysql
            - redis
        working_dir: /var/www/html
        networks:
            - laranet

volumes:
    mydb:
        driver: local
